# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Flutter
        uses: geowatson/flutter-latest@1.0.1
        with:
          args: upgrade

      - name: Get packages
        uses: geowatson/flutter-latest@1.0.1
        with:
          args: pub get
          
      - name: Build artifect
        uses: geowatson/flutter-latest@1.0.1
        with:
          args: build web -t example/lib.main.dart
          
          
      - name: Print path
        run: ls -a
